pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Install dependencies"){
            steps{
                sh 'pip install -r requirements.txt'
            }
        }

        stage("Test"){
            steps{
                sh 'pytest'
            }
        }

        stage("Build image"){
            steps{
                sh 'docker build -t python-app .'
            }
        }

        stage("Push to Docker hub"){
            steps{
                sh 'docker tag python-app chrispined/pythonStaff:python-app-1.0'
                sh 'docker push chrispined/pythonStaff:python-app-1.0'
            }
        }

        stage("Deployment"){
            steps{
                sh 'kubectl apply -f kubernetes/deployment.yaml'
                sh 'kubectl apply -f kubernetes/service.yaml'
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}