pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Build"){
            steps{
                sh 'go build main.go'
            }
        }

        stage("Unit Test"){
            steps{
                sh 'go test main_test.go'
            }
        }

        stage("Build Docker image"){
            steps{
                sh 'docker build -t go_app .'
            }
        }

        stage("Push the built Image"){
            steps{
                sh 'docker tag go_app chrispined/go_staff:go_app-1.0'
                sh 'docker push chrispined/go_staff:go_app-1.0'
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}