pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main"
            }
        }

        stage("")
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}