pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Build image"){
            steps{
                sh 'docker build -t java-crud-test .'
            }
        }

        stage("Push image"){
            steps{
                sh 'docker tag java-crud-test chrispined/javastuff:java-crud-test-1.0'
                sh 'docker push chrispined/javastuff:java-crud-test-1.0'
            }
        }

        stage("Start the test"){
            steps{
                sh 'docker run java-crud-test'
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}