pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Install dependencies"){
            steps{
                sh 'pip install -r requirements.txt'
            }
        }

        stage("Unit test"){
            steps{
                sh "pytest"
            }
        }

        stage("Run the application"){
            steps{
                sh 'pyhton3 app.py &'
            }
        }

        stage("Packaging"){
            steps{
                sh 'zip -r flask_app.zip *'
            }
        }

        stage("Archive"){
            steps{
                archiveArtifacts artifacts: 'flask_app.zip', fingerprint: true
            }
        }


    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}