pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Install dependencies"){
            steps{
                sh 'npm install'
            }
        }

        stage("Test"){
            steps{
                sh 'npm test'
            }
        }

        stage("Build Image"){
            steps{
                sh 'docker build -t node-app .'
            }
        }

        stage("Push image to DockerHub"){
            steps{
                sh 'docker tag node-app chrispined/NodeStuff:node-app-1.0'
                sh 'docker push chrispined/NodeStuff:node-app-1.0'
            }
        }

        stage("Deploy to K8s"){
            steps{
                sh 'kubectl apply -f kubernetes/deployment.yaml'
                sh 'kubectl apply -f kubernetes/service.yaml'
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}