source 'https://rubygems.org'

ruby '2.7.0' # Specify the Ruby version (optional)

# Web framework
gem 'sinatra'

# SQLite database driver
gem 'sqlite3'

# Testing framework
gem 'minitest'

# Gem to convert Ruby objects to JSON
gem 'json'
