apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: chrispined/pythonStaff:python-app-1.0
          ports:
            - containerPort: 8080
    