apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: NodePort
  selector:
    app: go-app
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000