pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Install dependencies"){
            steps{
                sh 'bundle install'
            }
        }

        stage("Unit test"){
            steps{
                sh 'ruby test_app.rb'
            }
        }

        stage("Run"){
            steps{
                sh 'ruby app.rb'
            }
        }

        stage("Package"){
            steps{
                sh 'zip -r ruby_app.zip *'
            }
        }

        stage("Archive artifact"){
            steps{
                archiveArtifacts artifacts: 'ruby_app.zip', fingerprint: true
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}