pipeline{
    agent any
    stages{
        stage("Checkout SCM"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Install dpendencies"){
            steps{
                sh 'npm  install'
            }
        }

        stage("Unit test"){
            steps{
                sh 'npm test'
            }
        }

        stage("Build image"){
            steps{
                sh 'docker build -t node-app .'
            }
        }

        stage("Push image"){
            steps{
                sh 'docker tag node-app chrispined/nodeApps:node-app-1.0'
                sh 'docker push chrispined/nodeApps:node-app-1.0'
            }
        }

        stage("Deploy to K8s"){
            steps{
                sh './scripts/prometheus-deploy.sh'
            }
        }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
        }
    }
}