apiVersion: apps/v1
kind: Deployment 
metadata:
  name: go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels: 
        app: go-app
    spec:
      containers:
        - name: go-app
          image: chrispined/goStaff:go-app-1.1
          ports:
            - containerPort: 5000
