pipeline{
    agent any
    stages{
        stage("Checkout"){
            steps{
                git branch: "main", url: ""
            }
        }

        stage("Build the application"){
            steps{
                sh 'go build main.go'
            }
        }

        stage("test the application"){
            steps{ //Creating a user
                sh 'curl -X POST http://localhost:8080/users -d "name=John Doe&email=john@example.com"'
                  //Reading the user
                sh 'curl http://localhost:8080/users'
                  //Updating user details
                sh 'curl -X PUT http://localhost:8080/users/1 -d "name=Jane Doe&email=jane@example.com"'
                  // Deleting user details
                sh 'curl -X DELETE http://localhost:8080/users/1'
            }
        }

        stage("Build an image"){
            steps{
                sh 'docker build -t golangApp .'
            }
        }

        stage("Tag and push image"){
            steps{
                sh 'docker tag golangApp chrispined/go-staff:golangApp-1.0'
                sh 'docker push chrispined/go-staff:golangApp-1.0'
            }
        }

    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}